import type { PropertyType } from "@qa/shared";
import type { Random } from "./random.ts";

/**
 * Nomes de ruas e trechos de descrição. As ruas são nomes plausíveis (muitos existem em SP),
 * sorteados por bairro — não pretendem corresponder ao bairro real.
 */

const STREET_KINDS = ["Rua", "Rua", "Rua", "Rua", "Avenida", "Alameda", "Travessa"] as const;

const STREET_NAMES = [
  "Augusta",
  "Haddock Lobo",
  "Oscar Freire",
  "dos Pinheiros",
  "Teodoro Sampaio",
  "Cardeal Arcoverde",
  "João Moura",
  "Fradique Coutinho",
  "Mourato Coelho",
  "Harmonia",
  "Aspicuelta",
  "Girassol",
  "Wisard",
  "Fidalga",
  "Purpurina",
  "Joaquim Floriano",
  "Tabapuã",
  "Pedroso Alvarenga",
  "Bandeira Paulista",
  "Clodomiro Amazonas",
  "Gomes de Carvalho",
  "Funchal",
  "Santa Justina",
  "Afonso Brás",
  "Ministro Rocha Azevedo",
  "Peixoto Gomide",
  "Bela Cintra",
  "Frei Caneca",
  "Caio Prado",
  "Maria Antônia",
  "Itacolomi",
  "Sergipe",
  "Piauí",
  "Maranhão",
  "Pará",
  "Albuquerque Lins",
  "Barão de Tatuí",
  "Cardoso de Almeida",
  "Monte Alegre",
  "Ministro Godói",
  "Turiassu",
  "Caraíbas",
  "Apinajés",
  "Venâncio Aires",
  "Clélia",
  "Guaicurus",
  "Tito",
  "Coriolano",
  "Pio XI",
  "Schilling",
  "Carlos Weber",
  "Domingos de Morais",
  "Sena Madureira",
  "Joaquim Távora",
  "Machado Bittencourt",
  "Tutoia",
  "Pelotas",
  "Afonso Celso",
  "Diogo de Faria",
  "Ibirapuera",
  "Jauaperi",
  "Canário",
  "Normandia",
  "Gaivota",
  "Pavão",
  "Bem-te-vi",
  "Inhambu",
  "Vieira de Morais",
  "Barão do Triunfo",
  "Princesa Isabel",
  "Pensilvânia",
  "Califórnia",
  "Michigan",
  "Indianópolis",
  "Jabaquara",
  "Cupecê",
  "Engenheiro Armando de Arruda Pereira",
  "Adolfo Pinheiro",
  "Padre José Maria",
  "Barão de Duprat",
  "Voluntários da Pátria",
  "Alfredo Pujol",
  "Doutor César",
  "Conselheiro Moreira de Barros",
  "Leite de Morais",
  "Copacabana",
  "Ezequiel Freire",
  "Tuiuti",
  "Itapura",
  "Serra de Bragança",
  "Emília Marengo",
  "Azevedo Soares",
  "Antônio de Barros",
  "Padre Adelino",
  "Juventus",
  "da Mooca",
  "Taquari",
  "Orville Derby",
  "Javari",
  "Paes de Barros",
  "Siqueira Bueno",
  "Celso Garcia",
  "Amador Bueno da Veiga",
  "Penha de França",
  "Gabriela Mistral",
  "Águia de Haia",
  "Itaquera",
  "Líder",
  "Nordestina",
  "Marechal Tito",
  "Pires do Rio",
  "das Flores",
  "das Palmeiras",
  "dos Ipês",
  "dos Jacarandás",
  "das Acácias",
  "das Hortênsias",
  "Professor Alfonso Bovero",
  "Heitor Penteado",
  "Cerro Corá",
  "Pio XII",
  "Jaguaré Mirim",
  "Corifeu de Azevedo Marques",
  "Vital Brasil",
  "Eliseu de Almeida",
  "Francisco Morato",
  "Giovanni Gronchi",
  "Jorge João Saad",
  "Doutor Guilherme Bannitz",
  "Hélio Pellegrino",
  "Santo Amaro",
  "Nossa Senhora do Sabará",
  "Interlagos",
  "Senador Teotônio Vilela",
  "Dona Belmira Marin",
  "Atlântica",
  "Guarapiranga",
  "Zachi Narchi",
  "Ataliba Leonel",
  "Nova Cantareira",
  "Imirim",
  "Casa Verde",
  "Engenheiro Caetano Álvares",
  "Inajar de Souza",
  "Elísio Teixeira Leite",
  "Raimundo Pereira de Magalhães",
  "Mutinga",
  "Fuad Lutfalla",
  "Edgar Facó",
  "Itaberaba",
] as const;

export function generateStreetPool(random: Random, size: number): string[] {
  const names = random.shuffle(STREET_NAMES).slice(0, size);
  return names.map((name) => `${random.pick(STREET_KINDS)} ${name}`);
}

const OPENINGS: Record<PropertyType, readonly string[]> = {
  APARTMENT: [
    "Apartamento amplo e bem iluminado",
    "Apartamento aconchegante e silencioso",
    "Lindo apartamento em prédio bem conservado",
    "Apartamento reformado, pronto para morar",
    "Apartamento com planta inteligente e ótima distribuição",
  ],
  HOUSE: [
    "Casa ampla em rua tranquila",
    "Sobrado espaçoso e bem cuidado",
    "Casa térrea com ótima iluminação natural",
    "Casa charmosa, ideal para família",
  ],
  CONDO_HOUSE: [
    "Casa em condomínio fechado com segurança 24h",
    "Sobrado em condomínio arborizado e tranquilo",
    "Casa em condomínio com lazer completo",
  ],
  STUDIO: [
    "Studio moderno e funcional",
    "Studio compacto, ideal para quem mora sozinho",
    "Studio novo em prédio com serviços",
  ],
};

const SENTENCES = [
  "Fica a poucos minutos de padarias, mercados e farmácias.",
  "A região conta com diversas linhas de ônibus e fácil acesso às principais avenidas.",
  "Os cômodos são arejados e recebem bastante luz natural durante o dia.",
  "O piso foi trocado recentemente e as paredes acabaram de ser pintadas.",
  "A cozinha é espaçosa e tem bancada em granito.",
  "Os quartos são bem divididos e cabem armários grandes.",
  "O bairro é residencial, com ruas arborizadas e pouco movimento à noite.",
  "Há escolas, academias e restaurantes a uma curta caminhada.",
  "A documentação está em dia e o imóvel está pronto para financiamento.",
  "A vista é aberta e o imóvel não tem vizinhos de frente.",
  "O condomínio tem manutenção em dia e administração organizada.",
  "Ideal para quem busca conforto e praticidade no dia a dia.",
  "As janelas antirruído garantem silêncio mesmo nos horários de pico.",
  "A área de serviço é separada da cozinha.",
  "O imóvel aceita propostas e o proprietário está aberto a negociação.",
];

/** Descrição de 2 a 7 frases; ~45% passam de 300 caracteres. */
export function generateDescription(
  random: Random,
  type: PropertyType,
  neighborhood: string,
): string {
  const opening = `${random.pick(OPENINGS[type])} em ${neighborhood}.`;
  const extra = random.shuffle(SENTENCES).slice(0, random.int(1, 6));
  return [opening, ...extra].join(" ");
}
